spring.application.name=stepmate_back

# === DataSource ===
spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://localhost:5432/stepmate_db
spring.datasource.url=jdbc:postgresql://stepmate-db.c054eoe2obxd.us-east-1.rds.amazonaws.com:5432/postgres
# spring.datasource.username=postgres
spring.datasource.username=foothaha
# spring.datasource.password=1234
spring.datasource.password=foothaha1234

# === JPA ===
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# === Server ===
server.port=8080


# === JWT ===
spring.jwt.secret=stepmate-jwt-secret-key-must-be-at-least-32-bytes-long

# === Google OAuth ===
google.oauth.client-ids=771220585977-0k8ge2320encvd1ad1pft8h9etfem2e1.apps.googleusercontent.com,771220585977-a83rkph72g892uafmmen7uqje5uphdkv.apps.googleusercontent.com

